name: Bump version
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
        MAJOR_STRING_TOKEN: BREAKING
        MINOR_STRING_TOKEN: feat
        PATCH_STRING_TOKEN: "*"
        INITIAL_VERSION: 1.1.0
